### ISSUE TITLE
The produced .app works only for current user, breaks if copied to another profile or computer

### ISSUE THREAD

**Issue by Alex1844** [Gcenx/WineskinServer#1]
Before first app launch, the folder "windata" in "Content\Resources" folder in wrapper has different permissions than the other files and folders. The "group" and "everyone" have read only permissions which breaks moving the files to ResoTemp folder on first launch, for any other user except the one who created the .app.
Changing the "group" and "everyone" permissions to "read and write" on "windata" and all enclosing subfolders and files, fixes it and wrapper can be copied to other users and computers

Can you please fix it in the wrapper Wineskin-2.8.7Beta5

Thanks

**Comment by Gcenx** [comment]
> Before first app launch, the folder "windata" in "Content\Resources" folder in wrapper has different permissions than the other files and folders. The "group" and "everyone" have read only permissions which breaks moving the files to ResoTemp folder on first launch, for any other user except the one who created the .app.
> Changing the "group" and "everyone" permissions to "read and write" on "windata" and all enclosing subfolders and files, fixes it and wrapper can be copied to other users and computers
> 
> Can you please fix it in the wrapper Wineskin-2.8.7Beta5
> 
> Thanks

I thought I fixed that with the Beta6 I just pushed but that was not the case, I checked over the relevant section and it has not really changed since the official version of Wineskin.

First WineskinLauncher would check if the Resources has permission for the current user and if not use chmod 777 to fix it, but that would it would now skip fixing windata or anything else that could have a problematic permission setting aka windata folder thats created. So instead I will remove the check so it just fixes the permissions regardless and reclusively. 

That has now solved that issue I will commit this time a working fix for that issue

**Comment by Gcenx** [comment]
@Alex1844 That should now be fully fixed in "Wineskin-2.8.8Beta1" I now also run chmod 777 before WineskinLauncher exits.

I tested they by creating a new wrapper using WS10WineCX18.0.0 and installing a game, after it was done I did not run it again, instead checking the newly created winedata folder and the permissions were set correctly.

**Comment by Alex1844** [comment]
Thanks,
I have verified "Wineskin-2.8.8Beta1" and it works fine.

Regards,
    Alex
________________________________
