### ISSUE TITLE
Launch EXE file (~wine/wine64) as sub process of WineskinLauncher

### ISSUE THREAD

**Issue by Rastafabisch** [Gcenx/WineskinServer#10]
This is actually a long standing issue (pre unofficial builds):
Launch Wrappers do not spring load in the dock, nor to they show up ins the macOS recent application section (e.g. Mojave Dock/Apple menu). I assume both named issues are correlated with each other. Hence only filing one ~~bug report~~ enhancement suggestion.

For packaging GTK applications _(or injecting environment variables or infos via a launcher too an applications Info.plist)_ I use the following (bash) code, in case it helps.
```
#!/bin/bash

# paths
name=$(basename "$0")

dirname=$(dirname "$0")

bundle=$(cd "$dirname/../../" && pwd)
bundle_res="$bundle"/Contents/Resources/

#exec=$name
exec="any_executable_name"

exec "$bundle_res""$exec" &>/dev/null
```

**Comment by Gcenx** [comment]
> This is actually a long standing issue (pre unofficial builds):
> Launch Wrappers do not spring load in the dock, nor to they show up ins the macOS recent application section (e.g. Mojave Dock/Apple menu). I assume both named issues are correlated with each other. Hence only filing one enhancement suggestion.

Wineskin doesn’t launch anything as a sub process Vitor and myself are aware of it, but it means possibly a larger rewrite of WineskinLauncher and Wineskin as a whole to use NSTask.

Not showing in recent is lightly related to us generating an invalid bundleID and the above wine not being a sub process of WineskinLauncher.

Not bouncing in the dock is not WineskinLauncher as it doesn’t show in the dock, wine/-preloader/wine64/-preloaded using macdriver generate the dock icon or lack of icon.
If I provided custom prebuilt Engines I could disable the dock icons then enable WineskinLauncher to show a dock icon. But that would then cause other issues when 

> For packaging GTK applications _(or injecting environment variables or infos via a launcher too an applications Info.plist)_ I use the following (bash) code, in case it helps.
> 
> ```
> #!/bin/bash
> 
> # paths
> name=$(basename "$0")
> 
> dirname=$(dirname "$0")
> 
> bundle=$(cd "$dirname/../../" && pwd)
> bundle_res="$bundle"/Contents/Resources/
> 
> #exec=$name
> exec="any_executable_name"
> 
> exec "$bundle_res""$exec" &>/dev/null
> ```

Thank you for the nice gesture, Wineskin.app handles the info.plist editing, along with editing the wine registry.
Currently all environment veriables are statically generated within WineskinLauncher, some are resolved within bash scripts we generate for bypassing SIP stripping.

**Comment by Rastafabisch** [comment]
Alright, thank you for the insights. As I recall the [WineBottler](https://winebottler.kronenberg.org) wrappers used to be spring loaded and quit, once the winemac.drv took over showing the applications/no logo. It might be worth a look even though it's not supported anymore, nor open source as far as I know. [This example of a ported application](https://github.com/nrlquaker/winbox-mac), which still currently works might be worth a look. (The /Contants/MacOS executable is actually a bash script, setting the environment variables.)

**Comment by Gcenx** [comment]
> Alright, thank you for the insights. As I recall the [WineBottler](https://winebottler.kronenberg.org) wrappers used to be spring loaded and quit, once the winemac.drv took over showing the applications/no logo. It might be worth a look even though it's not supported anymore, nor open source as far as I know. [This example of a ported application](https://github.com/nrlquaker/winbox-mac), which still currently works might be worth a look. (The /Contants/MacOS executable is actually a bash script, setting the environment variables.)

Looks like they did a nice job custom patching wine, also edited the initial stage script to copy the prefix into “Application Support” then use that for all following launches.

> Edit:
> I might have been wrong regarding not being [open source](https://bitbucket.org/winebottler/winebottler/src).

I have looked over the source before, that’s the reason I understood what needs to be implemented to resolve the problem within Wineskin.

> Edit2:
> Apparently at least with the included version of wine the linked wrapper behaves natively. (using macOS Mojave)

Yes it functions somewhat natively due to stage two launch that uses the scripts forwarded veriables onto the bundled patched version of wine.


Winebottler does the following;
- Initial launch startwine, setting all variables 
- Secondary launch  using veriables set from startwine
- Wine now launches

WineskinLauncher does the following;
- Set all variables, set BundleID, generate bash script, configure GPU information
- Wine bashscript used to bypass SIP stripping (can be dropped after switching to NSTask)
- Wine now launches

The bouncing is lightly when winestart launches.

I have already looked into implementing NSTask within WineskinLauncher’s main launch but I’m not familiar with its usage as the usage it’s much different then the current way launches are currently handled.
Really all launches should be handled using NSTask so anything launched would be owned by Wineskin.

**Comment by nagualcode** [comment]
how can I have more than one application on the same "bottler" / "drive_c" to save space with commom base?
I am using Wineskin on catalina (followed youtube instructions).

**Comment by Wowfunhappy** [comment]
> This is actually a long standing issue (pre unofficial builds):

Odd, funny thing. I'm using OS X 10.9, and I _only_ have this problem with Unnofficial Wineskin. It doesn't happen when I use Wrapper 2.6.2 from DOH123's official Wineskin.

**Comment by Gcenx** [comment]
> Huh, that's odd, because funny thing. I'm using OS X 10.9, and I _only_ have this problem with Unnofficial Wineskin. It doesn't happen when I use Wrapper 2.6.2 from DOH123's official Wineskin.

Wineskin-2.6.2 doesn’t launch wine as a subprocess, it just seems to be the case as by default Wineskin-2.6.2 uses its own embedded version of XQuartz where is removed it

**Comment by Wowfunhappy** [comment]
> Wineskin-2.6.2 doesn’t launch wine as a subprocess, it just seems to be the case as by default Wineskin-2.6.2 uses its own embedded version of XQuartz where is removed it

Ah, and I guess that can't be done in the new version, right? It was really nice to have the Dock work correctly in the old one, you could right click a running app and select "Keep in Dock", and everything functioned as you'd expect. With the current version, I have to drag Wineskin apps to my Dock before launching them, and then when I _do_ run them there's a second, duplicate Dock icon.

**Comment by Gcenx** [comment]
> Ah, and I guess that can't be done in the new version, right? It was really nice to have the Dock work correctly in the old one, you could right click a running app and select "Keep in Dock", and everything functioned as you'd expect. With the current version, I have to drag Wineskin apps to my Dock before launching them, and then when I _do_ run them there's a second, duplicate Dock icon.


It’s not that it can’t be done it’s more I won’t, doh123 said numerous times it was PITA to get XQuartz working the way she intended so it hadn’t been updated in years.

Since then macDriver has been improved to the point where it has less issues then when using X11 display driver on macOS.

The only real solution to making all launches a subprocess like CrossOver is by embedding something like pear and use the embedded version for launches. (CrossOver uses embedded pearl via a wine wrapper script)

**Comment by Gcenx** [comment]
The current master wrapper launches wine(64/32on64) in a manner that permissions are correctly inherited.

Having wine processes sharing an icon would require basically copying what CrossOver does but that then causes issues with inheriting permissions.

As wine(64/32on64) processes now correctly inherit permissions I consider this issue resolved
