### ISSUE TITLE
Multiple copies of Gecko are always installed in every wrapper created

### ISSUE THREAD

**Issue by CodingMarkus** [Gcenx/WineskinServer#100]
Creating a wrapper with engine `WS11WineCX64Bit20.0.2` and wrapper version `Wineskin-2.9.0.7-rc4`, gecko is always installed, no matter what you select in the dialog that pops up.

Even if I **deny installation**, gecko is found in `windows/syswow64/gecko/2.47.1/wine_gecko` and another installation is found in `windows/system32/2.47.1/wine_gecko` (each of them is 108 MB). Also there are always two MSI installer files located in `windows/Installer` with random naming (different names every time I create a wrapper) which are both setup files for gecko (50 MB each).

The only difference when I confirm the gecko installer dialog is that gecko is re-downloaded and reinstalled, which has no effect other than that another 50 MB are wasted for a download in `Temporary Internet Files`.

So altogether 316 MB are wasted for gecko, even if not required at all, and 258 MB are still wasted if required as in that case a single installation would have been enough (not two, no MSI installers, and the download in `Temporary Internet Files` should be deleted in the end).

**Comment by Gcenx** [comment]
You need to modify this issue and use one of the provided templates.

**Comment by CodingMarkus** [comment]
> You need to modify this issue and use one of the provided templates.

No, I don't. All the information asked in the template is there, all information that isn't, is irrelevant to the issue. And you haven't told that to other reporters to take care of their bugs (e.g. https://github.com/Gcenx/WineskinServer/issues/74). Either you fix this serious bug or you ignore it because it doesn't have the right form. Your choice. It's your product that will suck in the end because you don't listen to helpful reports and scare away people, who take themselves the time to write reports in the first place. With that attitude of you, I will better move on right now and turn my back on Wineskin as you just showed that this product has no future anyway, despite the fact that such a serious bug should have been noticed by yourself to begin with (you didn't notice that wrapper created with your new engine are far bigger than those created with previous once? Or you did notice but never cared to compare the wrapper content to find out why?) Farewell.

**Comment by Gcenx** [comment]
> No, I don't. All the information asked in the template is there, all information that isn't, is irrelevant to the issue. And you haven't told that to other reporters to take care of their bugs (e.g. #74). 

See https://github.com/Gcenx/WineskinServer/commit/6fa0a57c30a9e94d5b7f93d83a3f9df557905c14 after this I have required the issue template be filled out.

You haven’t provided your macOS version nor your hardware.

> Either you fix this serious bug or you ignore it because it doesn't have the right form. 

You didn’t provide your macOS version, that’s important lightly even more so for this particular case considering the default location of downloaded .msi installers would be ~/.cache/wine

That means ether your running macOS Catalina/macOS Big Sur or Winery Winery didn’t have the quarantine flag removed meanings it can’t access anything outside of itself causing this mess constantly.

What your requesting has only be added to upstream wine recently https://github.com/wine-mirror/wine/commit/5b362f07f67db5f90ac355c62a1f3d73658c4346, WineCX20.0.x is based on Wine-5.0

> Your choice. It's your product that will suck in the end because you don't listen to helpful reports and scare away people, who take themselves the time to write reports in the first place.

I’ve never considers this a product, see my above comments. I stated this project as the original Wineskin project hadn’t been updated in literally years but I liked it so decided why not try to keep it updated and add more features and provide modern wine packages.

> With that attitude of you, I will better move on right now and turn my back on Wineskin as you just showed that this product has no future anyway, despite the fact that such a serious bug should have been noticed by yourself to begin with (you didn't notice that wrapper created with your new engine are far bigger than those created with previous once? Or you did notice but never cared to compare the wrapper content to find out why?) Farewell.

So as I’m making it a requirement to fill out an issue template since it was added I have an attitude?, if only you known how many hours I’ve worked with PaulTheTall/Vitor and Wine developers on “bugs” only to find out later it was a known issue that would have been resolved instantly with a minimum amount of information.

Wrapper sizes have increased since Wine started it transition to PE format binaries, wine-gecko is small enough to not worry about or simply use a shared wine-gecko installed to avoid it.
