### ISSUE TITLE
Wine-preloader quiting when .exe quits

### ISSUE THREAD

**Issue by The-SamminAter** [Gcenx/WineskinServer#13]
I've noticed that Wine-preloader doesn't quit when the windows app quits. Is there a workaround for this?

**Comment by Gcenx** [comment]
> I've noticed that Wine-preloader doesn't quit when the windows app quits. Is there a workaround for this?

It should quit but it might take a little time for wineserver to kill all process

**Comment by The-SamminAter** [comment]
> > I've noticed that Wine-preloader doesn't quit when the windows app quits. Is there a workaround for this?
> 
> It should quit but it might take a little time for wineserver to kill all process

I timed it, it didn't quit after 10mins. Is there at least a way to switch the wineserver to my installed Wine Devel.app's wineserver manually?

**Comment by Gcenx** [comment]
Sometimes wine processes get stuck, on shutdown unofficial runs
“Wineserver -k” and the process name wouldn’t have been wine-preloader but something like
MyCoolWrapper48575884844Wine-preloader

I went with wines provided method then doh123’s way of hard killing the process since it can corrupt the prefix.

Commonly processes can get stuck when installing dotnet into a prefix or one of the application/game processes crashes, that results in a stuck wine process.

Not there wouldn’t be a way to use the wineserver version from the “Wine Devel.app” version mismatch is bad.

**Comment by The-SamminAter** [comment]
> Sometimes wine processes get stuck, on shutdown unofficial runs
> “Wineserver -k”, the process name wouldn’t have been wine-preloader but something like
> MyCoolWrapper48575884844Wine-preloader.
> 
> I went with wines provided method then doh123’s way of hard killing the process since it can corrupt the prefix.
> 
> Commonly processes can get stuck when installing dotnet into a prefix or one of the application/game processes crashes, that results in a stuck wine process.
> 
> No there wouldn’t be a way to use the wineserver version from the “Wine Devel.app” version mismatch is bad.
> 
> Edit;
> If you want to use an Engine like a Winehq app you can do it by clicking “Command Line Wine Test” it will launch Terminal and set PATH like the Winehq apps.

I meant more like is there a way that I can switch the wineserver to my installed Wine Devel.app's, so that I can use wine again?

After running `Command Line Wine Test`, I'm getting `wineserver: Can't check in server_mach_port
wine: for some mysterious reason, the wine server failed to run.` when trying to use Wine Devel.app

**Comment by Gcenx** [comment]
Reboot your Mac.

Something locked the interface that wineserver wants to use.

I’m not sure how that one happened since I’m usually running multiple Wrapper at once.

“Command Line Wine Test” only sets PATH and the Wineskin equivalent of DYLD_FALLBACK_LIBRARY_PATH for the launched Terminal session.
The “Wine Stable/Staging/Devel.app” only set PATH for that Terminal session.

But if wine somehow dies and locks the port that wineserver needs well not much can be done

**Comment by pauls0416** [comment]
I know this thread is nearly 2 years old but, as a programmer, I have to say, there is no reason for this!  Wine has been around for decades and the contributors STILL have not figured out how to have it clean up after itself?  Even if there were things that were totally out of my control on a particular OS (e.g. macOS), I'd figure out a way to clean up when the emulated EXE closes.  This is ridiculous.  One of those processes could incorporate a "watcher". 
Well, I better get going so I can kill a bunch of rogue wine processes....  I should probably write my own program that will watch for me.  If I'm playing UOoutlands, for example, and UOoutlands closes, ALL of these stupid wine processes (preloaders, etc) will get killed.

**Comment by itdir** [comment]
I know this has been closed, but I just installed the latest version of wine-stable available in brew (wine-6.0.2) and it is still a problem.

To launch another instance, I have to issue the shell command as the current user (no root priveledges needed):
`killall wine-preloader`

After that, the 7 wine64-preloader and the 1 wineserver instances close themselves.

**Comment by Gcenx** [comment]
@itdir no clue _why_ you’re talking about brew wine-stable package on this repository when this focuses on Wineskin not upstream wine specifically.

Upstream wine issues need to be reported to Winehq, you’ll lightly be asked to provide detailed logs and also retest on the latest wine-devel package.
