### ISSUE TITLE
Why can't I extract WS11WineCX64Bit19.0.1.tar.7z?

### ISSUE THREAD

**Issue by AlftheElf** [Gcenx/WineskinServer#149]
When I try to extract WS11WineCX64Bit19.0.1.tar.7z, I get 'Unable to expand "WS11WineCX64Bit19.0.1.tar.7z". It is in an unsupported format.'

This is using Mac Archive Utility, but it didn't work with Keka either.

**Comment by Gcenx** [comment]
Mac Archive Utility doesn’t support 7z, keka and some other third part utility’s do.

No clue why you’d even bother extracting the engine manually when Winery does this for you, not like the engine will fully work outside of Wineskin, also that engine was replaced with WineCX19.0.2-2 this has been available from Jan 9th this year.

**Comment by AlftheElf** [comment]
That's ok, I've worked it out now. I was using the 1.8.4 version using the source code (zip) download. Somehow I had 'No Wrapper Installed' and couldn't update. The plus button did not do anything, and I thought I needed to load the engine manually from the folder.

I found that the pre-release version works, but not from the sourcecode (zip); that has the same problem, and I expect I'm doing something wrong. I downloaded Wineskin.Winery.txz instead of the sourcecode, and this works perfectly as expected.

**Comment by Gcenx** [comment]
The only component that needs to be downloaded is the current version of Winery, If added a direct link to this on the readme.

The older version no longer works as I’d removed all of it’s related files, too many _guides_ directly linked to or out right ripped the files provided here and never linked back here, then when someone does end up here any issues are automatically invalid due to using the depreciated version of the project.
