### ISSUE TITLE
How does wine32on64 work?

### ISSUE THREAD

**Issue by highjeans** [Gcenx/WineskinServer#151]
I wanted to make a general 32 to 64 bit Mac app convertor for Macs specifically and I wanted to know where I could get the source code for wine 32on64. I want to pay a lot of games on my Mac but they are all 32-bit and crossover doesn't work.

**Comment by Rastafabisch** [comment]
[You might find this an interesting read](https://www.codeweavers.com/blog/jschmid/2019/9/10/so-we-dont-have-a-solution-for-catalinayet). It's a multi part writeup by the developers behind this work. (The follow-up articles are linked in the end.)

**Comment by Gcenx** [comment]
The simple explanation is `wine32on64` is a 64Bit implementation of 32Bit wine, this is getting implemented into upstream wine currently see the recent syscall work. If a games don't work with CrossOver it's not lightly to work with this as the CX Engines provided here is based on CrossOver but I do apply additional fixes and hacks.

@Rastafabisch PortingKit on macOS uses Wineskin ;) , depending on the ticket it ends up getting forwarded to my inbox.

**Comment by Rastafabisch** [comment]
Of course it does ; ) – I mentioned it in regards that there could be a "build script" readily available for some of the games @highjeans could not get to work with Crossover (presumably including checking [their catalog](https://www.codeweavers.com/compatibility)).

Regarding compatibility in general however there is one obstacle to be aware of: You **cannot** get anything to work yet, that is **32bit AND DirectX11 only** (for DirectX10 YMMV, DirectX9 most likely works), because the 32on64bit conversion layer does not handle Vulkan calls (yet). _Vulkan is the graphics language via which the translation from Windows' DirectX11 graphics language to other operating systems is handled (for macOS using [MoltenVK](https://github.com/iain-benson/MoltenVK)._

**Comment by highjeans** [comment]
> If a games don't work with CrossOver it's not lightly to work with this as the CX Engines provided here is based on CrossOver but I do apply additional fixes and hacks.

I am trying to run 32-bit **MacOS** pass on versions after Catalina.

**Comment by Gcenx** [comment]
> I am trying to run 32-bit **MacOS** apps on versions after Catalina.

I really don’t see how any part of crossover sources will be of any use other than how to run a 32Bit process within a 64Bit thread.

After that you’d need to deal with wrapping libraries that still exits as 64Bit to 32Bit, next would be dealing with now removed libraries like quicktime.framework.

To speed up the trunking generation CodeWeavers created there modified llvm/clang to help generate the trunked code but there target was running Windows software not native macOS software.

**Comment by Rastafabisch** [comment]
[This might also be an interesting read for you](http://netkas.org/?p=1491) @highjeans - though an older article it still might be feasible for you.

**Comment by Gcenx** [comment]
@Rastafabisch that’s only useful for initial testing but needing to change a boot argument isn’t a good option as you’ve seen from users here.

The major problem is the requirement of a macOS Mojave install for the required dylibs, shipping those within an app would be illegal that’s why CodeWeavers trunk to the native 64Bit dylibs.
