### ISSUE TITLE
Menu bar app name is always "Wine"?

### ISSUE THREAD

**Issue by i0ntempest** [Gcenx/WineskinServer#16]
"Menubar Name" in advanced settings has no effect in this modded version. Is it possible to show the correct app name in the menu bar? 

Also a problem about macOS 10.15: since it dropped 32bit support, is it still possible to run 32bit Windows applications?

**Comment by Gcenx** [comment]
> "Menubar Name" in advanced settings has no effect in this modded version. Is it possible to show the correct app name in the menu bar?

This worked on the official release by bundling a custom version of XQuartz that took name/icon set within Wineskin.app. This also happens for the official release when selecting macDriver.

_The way to achieve this now would require wine to be prepatched to accept an environment veritable for the menu name._

> Also a problem about macOS 10.15: since it dropped 32bit support, is it still possible to run 32bit Windows applications?

No.
This project uses **Winehq portable releases**, unless those run 32Bit code on macOS Catalina then Wineskin can’t run 32Bit code.

If the next CrossOver release does runs 32Bit code on macOS Catalina and the usual source release later includes the required changes then I could least provid a WineCX Engine based on that.

Unofficial Wineskin is 64Bit _(expect WSGamma due to no source)_
So pure 64Bit wrappers are possible even while using Winehq 64Bit releases.

For the forceable future I will only be officially supporting 10.8 to 10.14, as that’s what Winehq will be doing at this time.

**Comment by i0ntempest** [comment]
Thanks for the info, I might need to stay on 10.14 for a bit longer...
