### ISSUE TITLE
Winery freezes when installing any engine

### ISSUE THREAD

**Issue by TheDataDesigner** [Gcenx/WineskinServer#17]
Hey there. I'm running MacOS Mojave 10.14 and am having difficulties installing an engine from the unofficial winery 1.8.3. I've tried maybe a dozen different versions, including WS9Wine4.12.1, but every time, the app goes unresponsive and I have to force quit.

Steps
1. Downloaded winery 1.8.3
2. Moved winery file to application's folder
3. Opened application
4. Clicked + to add a new engine
5. Select an engine version
6. Click "OK" to start file download
7. File download progresses fine until it finished, then the app freezes.

![Screen Shot 2019-07-19 at 5 21 25 PM](https://user-images.githubusercontent.com/1761801/61570637-49446900-aa4b-11e9-80c3-478115660922.jpg)

![Screen Shot 2019-07-19 at 5 27 32 PM](https://user-images.githubusercontent.com/1761801/61570638-4cd7f000-aa4b-11e9-9783-724583628e49.jpg)

![Screen Shot 2019-07-19 at 5 27 56 PM](https://user-images.githubusercontent.com/1761801/61570641-51040d80-aa4b-11e9-939f-9e5745a55891.jpg)

I tried, unsuccessfully, to get some windows apps working with the official version before stumbling upon a thread on reddit where you suggested this version, so I was pretty excited to have something that works. If there is anything else I can do to help troubleshoot this, please let me know.

**Comment by Gcenx** [comment]
When the app goes unresponsive it should be displaying the busy window but that’s not always the case since changing over to XCode10.

When you see this just wait Winery is actually unpacking and prepacking the Winehq portable release into an Engine you can see this by looking inside /tmp. Also the 7z subprocess will be running, compression takes time and worse for 64Bit Engines.

If you download WS10WineCX18.5.0 you will notice it downloads then goes back to Winery quickly this is due to the Engine being provided directly as an Engine.



As I’m using GitHub to host this project I don’t really have any storage space for all the needed pre-made Engines so instead Winehq portable releases are downloaded and repackaged into Engines directly by Winery.

**Comment by TheDataDesigner** [comment]
Hey there, thanks for the response. I let the process sit overnight and I indeed returned with a successfully installed engine. I'll blame this one up to user error.
