### ISSUE TITLE
A lot… (using Catalina 10.15)

### ISSUE THREAD

**Issue by NBR101** [Gcenx/WineskinServer#23]
I'm having some problems getting wineskin to work, I don't know if it is because of the new OS.So to begin with, the update button to install a Wrapper works, but after completing the download nothing appears (checked the folders), I don't know were it goes, clicking the button again results in no different outcome…
So, as I couldn't get a Warpper through the app , I downloaded one of the internet, then when I finally click the Create New Blank Wrapper button, a message pops saying that my engines are either damaged or were open incorrectly, I tried a variety of engines even downloaded some manually and dragged them to their folder, and  I get the same the same problem

**Comment by Gcenx** [comment]
That’s strange I’ve had reports it functioned and made working wrappers that used 64Bit Engines.

At present I don’t officially support Catalina since no real viable Engine exist until CrossOver19 is released and source code gets upload, it also won’t be uploaded on day one but a few months later out of respect for all the work CodeWeavers do.

I’m not sure why it wouldn’t download anything, when I’ve tested it on Mojave with 32Bit code execution as disabled it still functioned.

The few reports I’ve had back said basic functionality was working on Catalina Beta, including making functional wrappers (64Bit only of course), as I currently don’t have Catalina installed in any fashion I’m unable to really resolve any issues at this time.

**Comment by emendelson** [comment]
This is very strange. When I downloaded from the Releases section here to my Catalina install, I saw exactly the same issues that NBR101 saw. But when I copied the app from my Mojave partition (I have a dual-boot machine), it worked perfectly and I was able to create and use an app using a 64-bit Windows app. 

My file-compare program (Beyond Compare) says that the app I downloaded from here and the one I copied from Mojave are identical. So this makes no sense at all, but it's definitely what's happening.

**Comment by Gcenx** [comment]
Sounds like gatekeeper is the issue, I’ll setup a Catalina install on an external drove at some point to try and figure it out

**Comment by emendelson** [comment]
I tried changing the bundle identifier in the Unofficial Wineskin Winery to one associated with my Mac Developer Account, and I was easily able to notarize the app. If you get in touch with me privately at the address on this page -

http://wpdos.org/feedback.html

- I'll send you a link to the notarized version for you to experiment with if you want. If you don't have an Apple Developer account, the people who use your program should be willing to help pay for one. (I'm certainly willing.)

**Comment by Gcenx** [comment]
So they forced notarize requirement early, the question is does the downloaded master wrapper work with the notarized version of Winery?

Since WineskinLauncher/Wineskin.app etc of course won't be notarized unless the Master Wrapper is also updated, but I really don't want do go changing that at the moment as i'm holding out for the next MoltenVK release since the Metal-3.0 branch is now merged.

**Comment by emendelson** [comment]
Notarization isn't forced. You can still run un-notarized and un-codesigned apps. So maybe it isn't actually Gatekeeper that's causing the problem here?

**Comment by Gcenx** [comment]
The app was singed (well should have been, with a free developers account) but not notarized using Xcode_10.3 that could be the reason for the issue.

It’s that or I need to bundle Winery into an signed xip/dmg/pkg, as it’s possible the extraction causing an issue, it’s happened before.

**Comment by emendelson** [comment]
It certainly had a code_signature inside it, so I should have guessed that it was code signed, but the bundle id seemed to be an arbitrary one. I used SD Notary to notarize it, not Xcode:

https://latenightsw.com/category/sd-notary/

**Comment by Gcenx** [comment]
Ive not looked over the code for Winery in months but I’m not surprised if the BundleID is weird.

I still need to decide what I’ll change with Wineskin overall before pushing a real update.

**Comment by Alex1844** [comment]
Emendelson,
how were you able to sign the app?
I am getting the following error even if I try to sign the empty wrapper
"unsealed contents present in the bundle root"

**Comment by emendelson** [comment]
In the SD Notary app, on the Advanced tab, I add checkmarks next to "Allow JIT-compiled code" and "Allow unsigned exec. mem." I'm not sure if both are needed, but the app gets signed when those two are checked.

**Comment by emendelson** [comment]
For those who read this on the mailing list, I've edited the previous comment to say that the app gets signed when I check only "Allow unsigned exec. mem." in SD Notary.

**Comment by Alex1844** [comment]
Why would it be impossible to sign or notarize a wrapper app?
Admittedly I do not know how to do it, but before I give up trying, I would like to know if it truly is impossible due to some objective reason, or is that just your guess.

**Comment by emendelson** [comment]
I don't know any objective reason, but every time I try, the initial signing effort fails with a "bad file descriptor" or some other error message, and (although I can't vouch for this) I once read an explanation on winehq.org why Wine apps can't be codesigned. You might want to search the winehq forum for further information.

**Comment by Gcenx** [comment]
I’m not too sure what can be done but code signatures break when an app bundle is modified.

The idea I’ve had is only adding the signature/notarize WineskinLauncher.
I’ve also read dylibs might also need to get a signature/notarized to function on Catalina but that I’m really not sure about.

**Comment by Gcenx** [comment]
![8B39DB75-ABEB-49D7-8F5E-F1AA8C809D45](https://user-images.githubusercontent.com/38226388/71419992-ae2a6d80-2640-11ea-87f9-66ee2dbad17c.jpeg)

I hadn’t pointed any updates here but I’ve been playing with WineCX19.0.0 on macOS Catalina, still need to make changes within Wineskin and hopefully my winetricks issue gets resolved.

@emendelson when using Wineskin on macOS Catalina did you get any issues access files within your users folders like desktop/download etc?
I need to figure out all the entitlements Wineskin will require now.

**Comment by emendelson** [comment]
I haven't tried this for a while (still mostly on Mojave, though I have a dual-boot system that can boot to Catalina for testing), but I remember that I got prompts telling me that the wrapper/app wanted access to my Documents folder (and I think also my Desktop folder). I changed the settings in my app to avoid both folders, but Catalina continued to ask about those folders for reasons I never figured out.

When you've got WineCS19.0.0 available for downloading from the Winery, I'll rush to give it a try...

**Comment by Gcenx** [comment]
I’ve gotten some of the backed done to support wine32on64 in the new wrapper I pushed earlier.

I’ve also pushed my current source [Unoffical_Wineskin](https://github.com/vitor251093/wineskin/tree/Unoffical_Wineskin) so if anyone wants to add/help/fix anything it’s now open.

**Comment by Alex1844** [comment]
Thanks.

I do not know where to start as I am complete noob regarding MacOS development. Can you please direct me where should I start looking for the issue I am having, namely when I add my app to the Full Disk Access, it works until I restart my Mac. After that my app is not even listed in Full Disk Access, and when I try to add it it does not stick most of the time. Once in a blue it will stick for a little while and then again i does not work. My uneducated guess is that it is somehow related to the bundle id.

**Comment by emendelson** [comment]
This seems to occur when the application is not notarized. There's hope that wineskin-related apps can be notarized. Meanwhile, you might try editing the Wineskin configuration so that you do not map folders like the desktop or Documents to drives in Wineskin. That seemed to work for me when I tried this some time ago.

**Comment by Gcenx** [comment]
I’ve disabled User mapping in the new wrapper to avoid that issue at least.

Notarizing seems to be only half the battle, it really will need to all be converted to using NSTask + signing/notarizing for everything to function.

I’d asked Vitor to make a simple NSTask launcher that was signed/notarized but I was still getting the same issues. I’m assuming the usage of bash scripts (for injecting dylib fallabck etc) is the root cause meaning we’re inheriting “bash” permissions over the Wrappers

**Comment by Gcenx** [comment]
@Alex1844 the wrapper not saying within permissions could be due to the BundleID being incorrectly generated (using spaces and any invalid characters will generate a weird BundleID) I’m assuming that’s that issue. I’d done a tweet to it in the last wrapper update but didn’t remove invalid characters yet.
The last wrapper update was mostly too;
- update the runtime
- add basic wine32on64 support
- slight BundleID generation change
- bundle patches winetricks for wine32on64
- some other small changes/updates/fixes

@emendelson to update on the above, I’ve asked Vitor to rewrite WineskinLauncher to use NSTask he’s already gotten a large chunk done.
I’m hoping to then drop the bash script wrappers when the above changes are done with added entitlements then be signed/notarized might resolve almost all the current issues (maybe not wine32on64 not sure just yet)

**Comment by emendelson** [comment]
OK - will be glad to report when things are ready. A Happy New Year to all.

**Comment by Alex1844** [comment]
Thank you. Happy New Year

**Comment by The-SamminAter** [comment]
Crossover 19 source code has been released: [https://media.codeweavers.com/pub/crossover/source/crossover-sources-19.0.0.tar.gz](crossover-sources-19.0.0.tar.gz)
Can this be used to create an official (unofficial) CX19 Wineskin, which fully works?

**Comment by Gcenx** [comment]
@The-SamminAter already built CrossOver19 from source see the screenshot a-few comments up.

Currently WineskinLauncher is getting a rewrite to hopefully resolve the Mojave and Catalina issues due to security changes.

WS11WineCX Engines built from CrossOver19 are done but require the above WineskinLauncher rewrite to be completed first.

## Current confirmed roadblocks;
- WineskinLauncher rewrite (command to NSTask)
- Paid Apple Developers license ($99 US a year)
- [Winetricks](https://github.com/Winetricks/winetricks/issues/1454) (needs to handle wine32on64)

**Comment by emendelson** [comment]
If you'll get in touch with me privately at the e-mail address on the page linked below, I might be able to help with the second roadblock. It's worth it to me to have a working system: 

http://wpdos.org/feedback.html

**Comment by The-SamminAter** [comment]
Couldn't a free developer Apple ID work? I don't see why a distribution licence is needed

**Comment by emendelson** [comment]
You can only notarize with a paid developer account.

**Comment by The-SamminAter** [comment]
> You can only notarize with a paid developer account.

What is notarizing?

**Comment by emendelson** [comment]
> > You can only notarize with a paid developer account.
> 
> What is notarizing?

Google will give you all the details.

**Comment by Gcenx** [comment]
@The-SamminAter I'm currently using a free developers account, you notice the need to still allows the software to run?

Apple now requires applications outside of the AppStore to be Signed & Notarized to function seamlessly.

@emendelson as I didn’t respond before, I’ll reach out about that once we’re finished with the current rewrite.

Here is the other reason for requiring a paid developers account, wine32on64 sets an executable bit to allow 32Bit code execution.

I’m not exactly sure if having WineskinLauncher signed & notarized will be enough with the Entitlements inheritance for wine32on64, it’s very possible each individual Engine will be required to be signed/notarized.

That’s something that we can not be 100% sure on currently until Winehq starts to provide wine32on64 builds, this wot happen until after Wine-5.0/CrossOver20 are both launched.

For the moment my test system of course has SIP disabled along with allowing unsigned code to speed up testing/development.

The only reason I’m able to test wine32on64 is due to having SIP disabled on my system, this isn’t something that we really want to be a requirement.

**Comment by Gcenx** [comment]
Closing this issue in favor of instead using #26 for all Catalina issues
