### ISSUE TITLE
latest update is not mature - bloated up with  bad backwards compatibility

### ISSUE THREAD

**Issue by johans3** [Gcenx/WineskinServer#27]
A) The new wrapper update disables winetricks, only an update brings wineskin back. We have to be online each time and we have to repeat updating winetricks for each wrapper we build. (I am not always online). This bug should be easy to solve.

B) i noticed the default wrapper size increases constantly. Years ago wrappers sizes were around 300 MB. The newest wrapper skyrocket to 1.2 GB standalone. 
Looking at a Cider-wrappers from 2012 we can see a size of 80 MB, it detected correctly my gpu and ran smootly like a dream. But because of the multiple windows feature i had to switch to wineskin. Honestly, i think wineskin is not allowed to concur with Crossover, because even the newest update is not able to detect my gpu, - currently it detects ATI HD 2900 XT - but mine is a AMD Radeon HD 7970 3 GB (which is also an old gpu nowadays). 
64 bit seems to cause a ton of problems - and all those who migrated tamely and quickly to Catalina. 

C) The latest update broke **Mod Organizer**, an app i use all the time - so, no occasional stuff i could trash/replace. Now, i tried:

- to assign XP to it in winecfg,
- tried winetricks, visual c lib 10,12,15
- winetricks directx9

in the hope to get the missing modules.

The qt framework is missing, and wineskin provides no qt winetricks. I get this error: 
i am using: 
Mod Organizer v1_3_11 installer

```
fixme:wer:WerSetFlags (2) stub!
fixme:heap:RtlSetHeapInformation 0x0 1 0x0 0 stub
fixme:actctx:parse_depend_manifests Could not find dependent assembly L"Microsoft.Windows.Common-Controls" (6.0.0.0)
err:module:import_dll Library Qt5Declarative.dll (which is needed by L"C:\\Game\\Mod Organizer\\uibase.dll") not found
err:module:import_dll Library Qt5Widgets.dll (which is needed by L"C:\\Game\\Mod Organizer\\uibase.dll") not found
err:module:import_dll Library Qt5WinExtras.dll (which is needed by L"C:\\Game\\Mod Organizer\\uibase.dll") not found
err:module:import_dll Library Qt5Gui.dll (which is needed by L"C:\\Game\\Mod Organizer\\uibase.dll") not found
err:module:import_dll Library Qt5Core.dll (which is needed by L"C:\\Game\\Mod Organizer\\uibase.dll") not found
err:module:import_dll Library uibase.dll (which is needed by L"C:\\Game\\Mod Organizer\\ModOrganizer.exe") not found
err:module:import_dll Library Qt5WebKitWidgets.dll (which is needed by L"C:\\Game\\Mod Organizer\\ModOrganizer.exe") not found
err:module:import_dll Library Qt5Widgets.dll (which is needed by L"C:\\Game\\Mod Organizer\\ModOrganizer.exe") not found
err:module:import_dll Library Qt5WebKit.dll (which is needed by L"C:\\Game\\Mod Organizer\\ModOrganizer.exe") not found
err:module:import_dll Library Qt5Gui.dll (which is needed by L"C:\\Game\\Mod Organizer\\ModOrganizer.exe") not found
err:module:import_dll Library Qt5Network.dll (which is needed by L"C:\\Game\\Mod Organizer\\ModOrganizer.exe") not found
err:module:import_dll Library Qt5Core.dll (which is needed by L"C:\\Game\\Mod Organizer\\ModOrganizer.exe") not found
err:module:LdrInitializeThunk Main exe initialization for L"C:\\Game\\Mod Organizer\\ModOrganizer.exe" failed, status c0000135
```

At this point i want to revert to the previous version of the your wrapper. I hope Time Machine can restore my previous Wineskin wrapper in home/library/Application support/wineskin. 
Sorry if i have this poor opinion of your latest update, as i know you all put a lot of time and effort in this project.

**Comment by Gcenx** [comment]
To address _bloated up with bad backwards compatibility_ almost all backwards compatibility was removed the moment I started working on this fork WineskinX11 and all related items were removed. That's the reason for requiring XQuartz for older Engines that I don't provide  
To support WineHQ & older Wineskin Engines down to 1.5.28, only 8 dylibs included for backwards compatibility within `wstools.bundle/lib/`


> A) The new wrapper update disables winetricks, only an update brings wineskin back. We have to be online each time and we have to repeat updating winetricks for each wrapper we build. (I am not always online). This bug should be easy to solve.

Wineskin-2.9.0.6 includes an embedded version of winetricks that's worked for PaulTheTall when testing on Catalina and myself on both Mojave and Catalina.
The bundled winetricks will be getting removed again as keeping a bundled version of winetricks means its outdated, however once its removed again it's easy to resolve on your end by doing the following
- make a new wrapper 
- update winetricks while online

copy `winetricks` & `winetricksHelpList.plist` 
`/Wrapper/Contents/Resources` now place those files into the master wrapper in the same location, now all created wrappers will include winetricks

<br>

> B) i noticed the default wrapper size increases constantly. Years ago wrappers sizes were around 300 MB. The newest wrapper skyrocket to 1.2 GB standalone.
> Looking at a Cider-wrappers from 2012 we can see a size of 80 MB, it detected correctly my gpu and ran smootly like a dream. But because of the multiple windows feature i had to switch to wineskin.

The master wrappers size is 338.6MB and that's the embedded runtime

Cider wrapper were based on an ancient version of wine that lacked 99% of current wine features that are not included out of box, new wineprefixes are heavy due to the transition from ELF to PE.

All WS9 Engines are downloaded via winehq then repackaged to Wineskin Engines, check current Wine releases and see the size increase, then make a clean wineprefix it's also huge now combine (Master Wrapper + Wine + WinePrefix) and that's before you install your software.

A Wine-5.0 wrapper with just gecko 1.24GB 
- MasterWrapper 338.6MB
- Wine-5.0 414.8 MB
- Wineprefix 480.7 MB

<br>


> Honestly, i think wineskin is not allowed to concur with Crossover, because even the newest update is not able to detect my gpu, - currently it detects ATI HD 2900 XT - but mine is a AMD Radeon HD 7970 3 GB (which is also an old gpu nowadays).
> 64 bit seems to cause a ton of problems - and all those who migrated tamely and quickly to Catalina.

Your not making much sense with this statement WineCX19.0.1 is built from CrossOver19.0.1 source provided by CodeWeaver.  
Now GPU detection is actually handled by [ObjectiveC_Extensions](https://github.com/vitor251093/ObjectiveC_Extension) so I'm sure Vitor would be interested in the GPU detection error.  
The GPU detection can also be disabled allowing wine to handle it directly, the option is under Screen Options.

> C) The latest update broke **Mod Organizer**, an app i use all the time - so, no occasional stuff i could trash/replace. Now, i tried:
> 
> * to assign XP to it in winecfg,
> * tried winetricks, visual c lib 10,12,15
> * winetricks directx9
> 
> in the hope to get the missing modules.
> 
> The qt framework is missing, and wineskin provides no qt winetricks. I get this error:
> i am using:
> Mod Organizer v1_3_11 installer
> 
> ```
> fixme:wer:WerSetFlags (2) stub!
> fixme:heap:RtlSetHeapInformation 0x0 1 0x0 0 stub
> fixme:actctx:parse_depend_manifests Could not find dependent assembly L"Microsoft.Windows.Common-Controls" (6.0.0.0)
> err:module:import_dll Library Qt5Declarative.dll (which is needed by L"C:\\Game\\Mod Organizer\\uibase.dll") not found
> err:module:import_dll Library Qt5Widgets.dll (which is needed by L"C:\\Game\\Mod Organizer\\uibase.dll") not found
> err:module:import_dll Library Qt5WinExtras.dll (which is needed by L"C:\\Game\\Mod Organizer\\uibase.dll") not found
> err:module:import_dll Library Qt5Gui.dll (which is needed by L"C:\\Game\\Mod Organizer\\uibase.dll") not found
> err:module:import_dll Library Qt5Core.dll (which is needed by L"C:\\Game\\Mod Organizer\\uibase.dll") not found
> err:module:import_dll Library uibase.dll (which is needed by L"C:\\Game\\Mod Organizer\\ModOrganizer.exe") not found
> err:module:import_dll Library Qt5WebKitWidgets.dll (which is needed by L"C:\\Game\\Mod Organizer\\ModOrganizer.exe") not found
> err:module:import_dll Library Qt5Widgets.dll (which is needed by L"C:\\Game\\Mod Organizer\\ModOrganizer.exe") not found
> err:module:import_dll Library Qt5WebKit.dll (which is needed by L"C:\\Game\\Mod Organizer\\ModOrganizer.exe") not found
> err:module:import_dll Library Qt5Gui.dll (which is needed by L"C:\\Game\\Mod Organizer\\ModOrganizer.exe") not found
> err:module:import_dll Library Qt5Network.dll (which is needed by L"C:\\Game\\Mod Organizer\\ModOrganizer.exe") not found
> err:module:import_dll Library Qt5Core.dll (which is needed by L"C:\\Game\\Mod Organizer\\ModOrganizer.exe") not found
> err:module:LdrInitializeThunk Main exe initialization for L"C:\\Game\\Mod Organizer\\ModOrganizer.exe" failed, status c0000135
> ```
> 
> At this point i want to revert to the previous version of the your wrapper. I hope Time Machine can restore my previous Wineskin wrapper in home/library/Application support/wineskin.
> Sorry if i have this poor opinion of your latest update, as i know you all put a lot of time and effort in this project.

If winetricks doesn't provide a verb I won't provide a custom verb, wineskin grabs winetricks from head, I currently apply three patches on top of winetricks head 2 for wine32on64 support and the last incase anyone uses it outside of wineskin.

The current version of **Mod Organizer**, is 1.40.4RC, it's zip only and functioned for me on macos Mojave using Wineskin-2.9.0.6 and WS11WineCX19.0.1 without the QT5 issue.

If you want to to use an older wrapper version you can download the older version since each master wapper is a commit on GitHub for example [Wineskin-2.9.0.5](https://github.com/Gcenx/WineskinServer/blob/12ab12202cd46685ce069073057928bc185c96f6/Wrapper/Wineskin-2.9.0.5.app.tar.7z)

**Comment by johans3** [comment]
thank you very much for your awesome info, Gcenx
