### ISSUE TITLE
Button "Download Packages Manually" leads to a dead folder in the cloud mega.nz

### ISSUE THREAD

**Issue by Drovosek01** [Gcenx/WineskinServer#354]
I use latest Wineskin Winery and if I press on button "Download Packages Manually"

![image](https://user-images.githubusercontent.com/29478700/219902618-9cc060ad-9d1b-4b19-8eb4-a82c7eed505d.png)

in my browser opening link - https://mega.nz/folder/7ZxFQYDB#7CJRmNuPReBcbsp0-rfjqg&/file/1026852291

I do not know what packages are in question in the conca, probably about downloading engines manually. If so, I think it would be useful to create a page here in the [Wiki](https://github.com/Gcenx/WineskinServer/wiki) section and write on this page that you can go to the [releases](https://github.com/Gcenx/WineskinServer/releases) section here on github open aseetes spoilers and manually download any .7z archive with any engine, and then move along the `/Users/YOUR_USER/Library/Application Support/Wineskin/Engines/` path and if you then run Wineskin Winery, then this manually downloaded engine will be in its list of installed engines.

Thank you

**Comment by Gcenx** [comment]
Yes the MEGA url was taken offline due to abuse, there’s really been no pressing need to update the Winery app at this time

Also there’s no really incentive to provide a guide for downloading/adding engines manually when they’re no point as all compatible engines are already listed.

Once I’ve removed an engine from the EngineList it’s considered unsupported.

**Comment by Gcenx** [comment]
As this project is hosted on GitHub and assets are attached to releases I think it’s not worth reinstating “Download Packages Manually” I’ll just just remove the button in a future Winery update.
