### ISSUE TITLE
re-run as a normal user

### ISSUE THREAD

**Issue by CaseyTT** [Gcenx/WineskinServer#38]
I try to install .exe installer on Catalina. However I can't install the software due to the following message. Is this same issue "https://forum.winehq.org/viewtopic.php?t=30206" ?
Please help me how to do. 

-- error message --
Installation has failed. Please re-run this installer as a normal user instead of "Run as Administrator".

**Comment by Gcenx** [comment]
For this to function wine-staging patches are required, crossover-wine doesn’t contain these patches

See https://bugs.winehq.org/show_bug.cgi?id=40613

I don’t see myself attempting to add these patches on top of crossover-wine source with all the hacks CodeWeavers needed to apply just to get it working on Catalina

**Comment by CaseyTT** [comment]
Thank you. Should we apply all patches for this issue ? hmmm. Because I have never been did this work, pls help me how to do.

**Comment by Gcenx** [comment]
The issue here is crossover-wine-19 source is a super hacked up version of Wine-4.12.1, I've back ported a few patches into it but most items can't easily be added into the codebase due to all the hacks required to get wine functional on macOS Catalina.
Wine-Staging-4.12.1 should contain the needed patches but I can't be sure they would apply onto crossover-wine-19 source.

You would be required to setup a development environment that contains all required dependencies see [macports-wine](https://github.com/Gcenx/macports-wine), you'd also need to compile CodeWeavers custom LLVM/Clang-8 from source as that's required to compile `wine32on64` 

All in all I don't believe it's currently worth all the effort required to potentially get a wine-staging feature into crossover-wine (WineCX), it might be a something that could be required for CrossOver-20 as thats currently being worked on.
