### ISSUE TITLE
Apple Game Porting Toolkit Integration

### ISSUE THREAD

**Issue by MarshallBelles** [Gcenx/WineskinServer#417]
Apple just released a major milestone for Mac users and developers with their game porting toolkit. With some hacking around, I was able to get Diablo 4 running on an entry-level M1 MacBook Air with 8GB ram and 256gb SSD.

Not joking, it ran on medium settings at ~30fps, native resolution. Using an external 1080p display, however, was abysmal at 10-15fps, which is weird because it is lower resolution so I guess there’s some overhead with the external USB-C display adapter, but anyways that’s beside the point. 

It was an absolute PITA to setup, requiring a beta OS install, XCode beta, compilation of like a hundred projects (thankfully this was automated), terminal knowledge, etc. 

There is like no way the average person would be willing and able to use it. This is where Wineskin comes in! I would like to propose an integration of Apple’s D3DMetal into this project. This is going to need a pretty hefty research spike. There is some talk about licensing issues for commercial projects, but I don’t think that applies here. I’m not a legal expert by any means so the licensing needs to be reviewed by one.

**Comment by MarshallBelles** [comment]
Instructions for how to use the toolkit are here:

[Game Porting Toolkit Instructions ](https://www.applegamingwiki.com/wiki/Game_Porting_Toolkit)

**Comment by Gcenx** [comment]
Please don’t link to third-part sites when Apples own documentation provided inside there dmg.

I’m well aware of this see https://github.com/Gcenx/WineskinServer/discussions/409

> It was an absolute PITA to setup, requiring a beta OS install, XCode beta, compilation of like a hundred projects (thankfully this was automated), terminal knowledge, etc.

Only two things were compiled but if your not use to this it might seems like it’s doing more. The others were prebuilt by brew.

> There is like no way the average person would be willing and able to use it. This is where Wineskin comes in! I would like to propose an integration of Apple’s D3DMetal into this project.

I can make it compatible with d3dmetal however I can’t include the files due to Apple restrictive license.

<br>

I’ve been testing d3dmetal while it’s nice for some titles it also breaks more than it fixes, hopefully Apple continues to improve this so it becomes more usable by the time macOS Sonoma releases.

**Comment by Gcenx** [comment]
> @Gcenx is it possible to compile d3dmetal for wineskin on Ventura? If so could you share the basic steps? I would be so keen to try, but don't really want to upgrade my OS.

@palmerj there is no compiling d3dmetal as it’s closed source with a very restrictive license meaning even when an Engine is compatible with Apples dlls/dylibs/framework I won’t be legally allowed to provide them within said Engine

It’s going to require at minimum of one manual step possibly multiple.

Also d3dmetal doesn’t official support macOS Ventura, I know there videos showing Diablo4 running’s but that’s lightly an exception not the rule as some features require Metal3.1

**Comment by Gcenx** [comment]
> Ok thanks. So just clarifying: the d3dmetal module is only shipped as a binary library, under a commercial licence and is linked to new Sonoma libraries/frameworks containing required newer APIs

It’s not a commerical license it’s much more restrictive, technically it also works on macOS Ventura but only like Diablo4 worked that I’m aware of.

> Are you referring to taking the d3dmetal module and packaging/modifying (as in manually updating dependent dynamic libraries calls) it to work with WineCX on Sonoma.

No I’m referring to applying _only_ the required changes from Apple to allow an end-user to drop M3DMetal into a compatible Engine and use it.

The actual _requires_ changes to make D3DMetal usable is tiny, I’m applying only those changes along with changes to preloader to work on macOS Sonoma.

**Comment by Gcenx** [comment]
> I see that [whisky](https://github.com/IsaacMarovitz/Whisky) allows you to user supply Game_porting_toolkit_beta.dmg and works on MacOS 13.1+. Could something like this also be done on Wineskin? I don't like the look of Whisky too much as it doesn't provide many required features.

Not sure I'll implement a feature to directly copy in the required files, probably just provide a guide on how to import the files into the Engine that supports using D3DMetal the Engine could always be repackaged on the users system so they could directly make D3DMetal supported wrappers from then on.

**Comment by Gcenx** [comment]
Not sure why Whisky is advertising macOS Ventura 13.1 support when GPT requires Metal feature that we’re not introduced until macOS Ventura 13.3 and even more so really requires macOS Sonoma (Metal3.1)

<br>

I didn’t rush support for D3DMetal in Wineskin as things need testing to ensure it doesn’t introduces regressions (apple-wine introduces regressions)

Whisky is affected by the above regressions and other issues.

I also only have a base m1 mini with only 8GB of ram so I can’t do much testing of D3DMetal since that lists a minimum of 16GB of ram. _And no I can’t use donations to get a better system as nobody donates so yeah…._

**Comment by Gcenx** [comment]
When I get time I'll prep some documentation for integrating D3DMetal into supported Engine(s)

<br>

@palmerj thank you for the donation those are always appreciated.

**Comment by Gcenx** [comment]
Manual installation of D3DMetal instructions can now be found https://github.com/Gcenx/WineskinServer/issues/420
