### ISSUE TITLE
Any success with EA App?

### ISSUE THREAD

**Issue by vualeks** [Gcenx/WineskinServer#435]
Hi,

I'm trying to install EA App on Wineskin Server and I managed to get it passed the main install and activation part. I've got it in a Steam wrapper that already has Steam working and I've added some components according to this guide https://github.com/kageurufu/steamdeck-tricks/blob/main/ea-app.md (corefonts d3dx9 d3dcompiler_43 d3dcompiler_47) but I only get the login screen without anything visible inside. I guess that web part is not rendering.  Screenshot and LastLog are attached. Anyone has some suggestions what could I try more?

OS: 13.4.1
Winery version: 1.8.4
Master Wrapper version: 2.9.1.9
Engine version: WS11WineCX64Bit22.1.1-8
Hardware: MacBook Pro 16 2021 M1

Thanks

[LastRunWine.log](https://github.com/Gcenx/WineskinServer/files/12208090/LastRunWine.log)
<img width="534" alt="Screenshot 2023-07-29 at 23 00 19" src="https://github.com/Gcenx/WineskinServer/assets/13743682/6eaf8da3-38c0-4fea-9141-5f96866838c1">

**Comment by Gcenx** [comment]
The EA app is known not to work in CrossOver-22.1.1.

Since you’ve already attempted to install EA app you’ll need to trash the wrapper and start over.

The `origin` verb has some workarounds so Steam will believe the EA app was installed and allow you to launch your EA games from within Steam and it will automatically launch Origin then your game.
