### ISSUE TITLE
How to create path for OpenBUGS into R using R2OpenBUGS with new Wineskin-Winery 1.8.4.1/Wineskin2.9.06-1 on MacOS Catalina 10.15.5

### ISSUE THREAD

**Issue by Jrogan23** [Gcenx/WineskinServer#45]
Hi!
 
I recently downloaded the new Wineskin-Winery 1.8.4.1/Wineskin2.9.06-1 onto my mac adapted for the limitations for MacOS Catalina 10.15.5 that caused old versions of Wine to no longer work. I downloaded it so that I could download the Windows program OpenBUGS and use R2openBUGS in R to use the program. I am trying to figure out how to call OpenBUGS into R with R2OpenBUGS with the new wineskin/wineskin-winery version. **(I posted this on an R forum and was told a Wine forum may be more suited **
 
 I found older code using the Wine argument in R2OpenBuGS, but I think the path has significantly changed with the new version of Wineskin which is not downloaded using homebrew as old versions of Wine were. I think I just need to figure out how to create the correct path for the new version of wine--I do not know if this is possible using the old wine argument designed for older versions of wine.
 
I downloaded the new Wineskin from here: https://github.com/Gcenx/WineskinServer/releases 
 
The old path for OpenBUGS and R2OpenBUGS for older versions of wine I found were: WINE="/usr/local/Cellar/wine/2.0.4/bin/wine"
WINEPATH="/usr/local/Cellar/wine/2.0.4/bin/winepath"
OpenBUGS.pgm="/Applications/OpenBUGS323/OpenBUGS.exe"
 
But trying to do the same, I received the error message: "Error in bugs(spp.data, inits, params, "model1.txt", debug = T, n.chains = nc, : unused argument (OpenBUGS.pgm = bugs)"
 
Part of my confusion is what the difference is between the arguments "wine" and "winepath". There is also an argument "newWINE" that says: "Use new versions of Wine that have ‘winepath’ utility", but I don't know if my version of wine has this, and how this argument is then written.
 
If I go to the "get info" on where my wineskin app is on my computer, the path is (while redacting my name) "/Users/firstname_lastname/Applications/Wineskin/Wineskin-2.9.0.7.app". Maybe this would work? But I don't know if this would be in the argument for wine, or winepath. 
 
I think perhaps if I can adapt the path, it will work. But I'm not sure exactly what is needed, particularly for the new version of wine for MacOS Catalina, and if it is just that the old wine arguments don't work with the new version of wine? If anyone could help I would sincerely appreciate it.  Even if someone can point me to another Wine specific forum or mailing list if this is not the appropriate place. Thanks!!

**Comment by Gcenx** [comment]
Your attempting to use Wineskins master wrapper (a blank app bundle with wine dependencies/tools) as if it’s a wine binary.

Instead you need to use a copy of wine directly;
```
brew tap gcenx/wine && brew cask install wine-crossover
```
The above command will add my brew tap then install the custom package and add symlinks into /usr/local/bin

You can then adapt your environment variables 

```
WINE="/usr/local/bin/wine"
WINEPATH="/usr/local/bin/winepath"
OpenBUGS.pgm="/Applications/OpenBUGS323/OpenBUGS.exe"
```

I can’t be sure if you missed anything as you never link to where you obtained the information your trying to use.

**Comment by Jrogan23** [comment]
Hi,

Thanks so much for your help! Ok, so I put brew tap gcenx/wine && brew cask install wine-crossover into the terminal, yes? And then the path I showed (and you pasted again as well) to use wine to open OpenBUGS in R should work?

This is where I had seen old instructions to create the winepath to OpenBUGS using the previous version of wine:
[(https://oliviergimenez.github.io/post/run_openbugs_on_mac/)]

Thank you!

**Comment by Gcenx** [comment]
Yes you run that command from terminal, it will add my brew tap and then install the custom `wine-crossover` package.

The second section I altered the settings to match using the newly installed custom wine package.

The custom package `wine-crossover` will function on OSX10.9, macOS Catalina 10.15.4 and above, also macOS Big Sur on an Intel based mac

**Comment by Jrogan23** [comment]
Thanks so much! I did initially get errors when downloading the first time, but after troubleshooting with homebrew I tried updating and trying the download again and it worked that time!

**Comment by EMDLvdHeijden** [comment]
Hope I may still ask a question concerning this as I'm trying to do this, but my R still seems to struggle to find openBUGS.

I am on a Macbook Pro 2016 running on Big Sur 11.6 and running R 4.1.1.

I finally managed to install openBUGS323 through wine-crossover, that I installed using the commands

`brew tap gcenx/wine`

followed by

`brew install --cask --no-quarantine wine-crossover`

And

`wine64 OpenBUGS323setup.exe `

(This after first having downloaded and installed and uninstalled wine and wine-stable and gcenx-wine-stable because they wouldn't work.)

In R I run:

`WINE="/usr/local/bin/wine"`
`WINEPATH="/usr/local/bin/winepath"`
`OpenBUGS.pgm="/Applications/OpenBUGS323/OpenBUGS.exe"`

And then try to use openBUGS, but I get the following error:
Error in bugs(data = dat, inits = inits, parameters.to.save = paras, n.iter = niterations +  : 
  Cannot find the OpenBUGS program

I'm working in an R Markdown, where I specified the working directory in the setup chunk, not sure if that could be causing a problem? But if I add "setwd("~/") to the chunk that I'm trying to use openBUGS in, it doesn't help.

I've also restarted my mac in the mean time, in case that was necessary. Also didn't help.

I'm not sure what to do next. Could you please help me? Hope I've supplied enough info for you to know what I'm trying to do.  Thanks!
