### ISSUE TITLE
Mapping and/or permission issues with Documents folder sync in iCloud

### ISSUE THREAD

**Issue by PlanetIrata** [Gcenx/WineskinServer#50]
When the macOS Documents folder is stored and synchronized in an iCloud drive, our Wineskin application encounter [this type of errors](https://github.com/Gcenx/WineskinServer/issues/26#issuecomment-641945275) despite the fact that we answer "Yes" on first launch when the Files and Folders access authorization is required.

Once the Documents folder is unchecked for synchronization in iCloud settings, everything is fine again.

May be a Catalina Issues with non notarized Wineskin app ?

**Comment by Gcenx** [comment]
To get this working I believe your correct the resulting Port will need to be code signed and notarized.

But Wineskin ports are self modifying app bundles so these will break, the only current solution I’ve thought of is having the included Wineprefix copy into a user location on first launch and always us that after the initial copy so the bundled Prefix never changes.

CodeWeavers do something similar with there FF port

**Comment by Gcenx** [comment]
@PlanetIrata I don’t use iCloud but this might be resolved I’m with the newer pre-release version of Winery/master wrapper combination as it seems to resolve the tccd load issue and request permissions more correctly.

Just make sure to grab the newer version of winery I uploaded to pre-releases today or the new wrapper will fail to create wrapper, also older wrapper can not be upgraded to this version without major issues due to all the internal changes.

**Comment by chucker** [comment]
@Gcenx yes, I think so. I had an issue where an app tried to write a shortcut to the Desktop, and failed. (My Desktop is synced to iCloud). After switching from 2.9.0.7-rc1 to rc2, it worked.

**Comment by Gcenx** [comment]
@chucker could you try making a text document on your iCloud desktop and edit it using say notepad/wordpad from within Wineskin?, if that works I’d say that confirms this was resolved.

For the wrapper just ensure it’s _not_ using the default name of `MyCoolWrapper`
