### ISSUE TITLE
CoreAudio/CoreMidi Support

### ISSUE THREAD

**Issue by forgetthespeech** [Gcenx/WineskinServer#51]
WS11WineCX64Bit19.0.1-1 & Wrapper v. Wineskin-2.9.0.6-1

Software is BladeEdit350, a program used to control an audio matrix router made by Sound Sculpture. Using the versions listed above, I was able to get the program to open up, but it seems the Midi communication is broken. The hardware responds to commands from the program, but the program does not see responses from the hardware. Developer is in communication with me about their progress, they currently support High Sierra, and he is stumped about the Midi problem. I've verified with the developer that the unit is sending the appropriate response SysEx messages, it just doesn't pass through to the software. Thanks for any help!

**Comment by alexsarmiento** [comment]
I am getting a similar problem with other midi software. Zoom Edit&Share won't show my multi-effects processor. KontrolEditor17 has problem communicating with my nanopad (just for testing since there's a macos version that just works.)

Midi-OX shows that the midi devices are there but can't receive any input. As a workaround I must use the RTP-MIDI driver from a Windows machine to operate my multi-effects processor. ugh!

**Comment by forgetthespeech** [comment]
I have to use this software for my gig, and there is no OS X version, so I just downgraded to Mojave on my MBP. Not ideal but I couldn't wait around for a fix. Thanks for the info, glad it's not just me.

**Comment by alexsarmiento** [comment]
Yes, I just found out that the same issue was reported by other people for other midi software at crossover for version 19 . No MIDI input. Sigh. 

https://www.codeweavers.com/support/forums/general/?t=27;mhl=222675;msg=222675#msg222675

**Comment by Gcenx** [comment]
Yet another trunking related issue, this is something that out of my control
