### ISSUE TITLE
Fix building new engines

### ISSUE THREAD

**Issue by ganthore** [Gcenx/WineskinServer#7]
Building new engines doesn't appear to be as straightforward as one would expect... The base unofficial app won't let you install a base build engine to build a new engine using the unofficial wineskin app from a vanilla macOS installation. I'm able to get a base engine profile to load using the older wineskin, but once I install that, then try to  use that with the unofficial wineskin, I get various build errors which suggests to me I'm not using the GUI app as intended...

Is there a well documented, standard way to build new engines that the community can use? I have all sorts of patches I'd like to compile into an engine to run thorough wineskin in macOS.

**Comment by Gcenx** [comment]
I currently don’t provide an EngineBase for Unofficial.
As you seen the EngineBase from official Wineskin has stopped working since El Capitan or should I say with the introduction of SIP.

I have previously updated the scrip within EngineBase to function again but I haven’t reworked the libs & headers for a good while.

I’m afraid there is currently no good documentation for building Wine for macOS as a whole at the moment.

I could properly throw something together but it would only include the bare minimum to compile a working version of wine.

**Comment by ganthore** [comment]
I'd be fine with a bare minimum working version of wine that compiles.

**Comment by Gcenx** [comment]
I have made progress on this but have been slowed due to bugs with osxcross based winebuild. Unable to install dotnet/vcrun.

I will test if direct compiles can install dotnet/vcrun if they can then I can push the Winery winebuild system out.

It currently requires OS X 10.9 or greater as I’m using XCode Command Line Tools to compile wine. That makes it easy to install if missing and just grab the required 10.11SDK from GitHub.

**Comment by Gcenx** [comment]
@ganthore I’m sorry this is taking longer then I anticipated thanks to real life and other issues like #9 thanks to a broken port of Gnutls from packages.macports.

But the good news is someone reliable is testing out a modified version of the updated build script, afew modifications and it should be good to go.

The updated EngineBase compiles something Winehq like, I would like to hold off until I can include Gnutls(needed for ssl) and ffmpeg(needed for wma decoding)

**Comment by Gcenx** [comment]
An updated EngineBase was completed, it still requires external testing.

I will open a separate repository for the new EngineBase when I have time as at precent that’s something I don’t have much of.

**Comment by ganthore** [comment]
Any way I can chip in and help ya test things out? Is there a repo I can pull from?

**Comment by Gcenx** [comment]
> Any way I can chip in and help ya test things out? Is there a repo I can pull from?

Honestly real life has been hectic, along with the recent upstream wine requirement increases and now with wine-4.8 wine64 requiring mingw-w64 to even build correctly since the fallback of using gcc/clang is also broken....

Current wine sources need the latest versions of;
- bison
- automate
- mingw-w64
Maybe I'm missing something here?

I'm thinking of using brew to install those dependencies, not sure it I should make it a prerequisite or embed checks for brew and installing brew/items as needed.

**Comment by Gcenx** [comment]
Once the new VulkanSDK is avalaible I’ll upload the current script and runtime to another repository for external testing.

**Comment by Gcenx** [comment]
@ganthore sorry I’ve been busy with irl, I’ll upload the current files and add you so your able to test it out before a more general release. 

Winery needs to be updated for the script changes but in holding off until Unofficial is changes are merged back upstream
