### ISSUE TITLE
Mac won't open this software

### ISSUE THREAD

**Issue by elise12192** [Gcenx/WineskinServer#71]
Hello,

I am trying to use this software to install a Windows game on my MAC. I'm using the Catalina 10.15.6 OS and was having trouble with other Wineskin downloads so I thought I'd try yours.

When I did so, I wasn't able to open it. I got this message from Apple:
 “Unofficial Wineskin Winery” can’t be opened because Apple cannot check it for malicious software

Is there a fix for this?

**Comment by Gcenx** [comment]
The problem is you have gatekeeper enabled and currently Winery/Wineskin isn’t code-signed.

Trash the extracted copy of Winery and open terminal and run the following command

```
xattr -drs com.apple.quarantine ~/Downloads
```

This will remove the quarantine flag from everything with your users /Downloads directory. Also don’t unpack the archive with Keka at that will re add the quarantine flag after extraction.
