### ISSUE TITLE
No Man's Sky - Apple Silicon

### ISSUE THREAD

**Issue by philspence** [Gcenx/WineskinServer#95]
**Environment:**
 - OS: 11.2.3
 - Winery version: 2.9.0.7-rc4
 - Master Wrapper version: 1.8.4.2
 - Engine version: WS11WineCX64Bit20.0.2
 - Hardware: M1 Mac Mini

**Describe the bug**
No Man's Sky (Steam version) launches to a black screen which exits followed by the message:

"The Vulkan driver for 'Apple M1' reports that it does not support wide lines'

**To Reproduce**

1. Run `winetricks dxvk_macos.verb`
2. Install game on Steam
3. Rename vulkan-1.dll in "drive_c/Program Files (x86)/Steam/steamapps/common/No Man's Sky/Binaries" to vulkan-1_backup.dll (not doing this results in the game being unable to find vulkan)

Anyone have an idea what this error means? Can't seem to find it reported anywhere else.

**Comment by Gcenx** [comment]
Not sure why your installing DXVK for this when the game has a native Vulkan render.

Hum not sure if that’s MoltenVK saying it doesn’t support that feature or if the M1 GPU is at fault, to see if the issue is related to MoltenVK being older grab https://github.com/Gcenx/MoltenVK/releases/download/v1.1.2/macos_dxvk_patched.tar.xz extract that and resolve the copy of libMoltenVK.dylib within the wrappers Frameworks directory with the one from that archive.

If this still doesn’t work then MoltenVK doesn’t provide the needed Vulkan extensions.

**Comment by Gcenx** [comment]
It’s ether libMoltenVK doesn’t provide the needed extension, or the Apple Silicon GPU doesn’t support it.

I’m not too sure on what’s ones at fault here.

**Comment by JoachimM7** [comment]
@Gcenx: Thanks for the patched file. Why is that one not in the main wrapper? With the main wrapper I cannot play Age of Empires 2 Definitive Edition. With this .dylib it's working perfectly!!

**Comment by Gcenx** [comment]
@JoachimM7 the build of libMoltenVK included in the current master wrapper is what’s provided by CodeWeavers 20 sources, they didn’t force enable swizzles the affects of this went discovered until well after the wrapper was provided publicly.

The next wrapper update will include a version that does force enable swizzles so Intel GPUs will be happily function.

Im not sure on the exact version that will be bundled as later versions have regressions in Apple Silicon devices, so I’ll lightly keep the current v1.1.0 but with swizzles force enabled.
